from .admin_view import *
from .airline_view import *
from .auth_view import *
from .country_view import *
from .customer_view import *
from .flight_view import *
from .group_view import *
from .permission_view import *
from .ticket_view import *
from .user_view import *