# Generated by Django 4.1.7 on 2023-04-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0002_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_all_users', 'Can view all users')]},
        ),
    ]
