# Generated by Django 4.1.7 on 2023-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'permissions': [('can_view_countries', 'Can view countries')]},
        ),
    ]
