# Generated by Django 4.1.7 on 2023-04-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0004_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
