# Generated by Django 4.1.7 on 2023-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0006_user_user_role_alter_user_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
