# Generated by Django 4.1.7 on 2023-04-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0008_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
