# Generated by Django 4.2.4 on 2023-08-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0010_alter_ticket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
