# Generated by Django 4.2.4 on 2023-08-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightapp', '0012_delete_usergroup_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airlinecompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
    ]
